### ISSUE TITLE
Open up a terminal window in the macos_burst directory.

### ISSUE THREAD

**Issue by ChunkyVittles** [beatsbears/macos_burst#1]
Hi

First thanks for doing this - I have been trying to install a wallet on iMac but so far have been unsuccessful. I feel like as soon as someone creates software which is just a "one click and it runs automatically" solution Burst will get more widely adopted, etc.. I keep hitting walls and am wondering if you might be willing to help. (I also noticed you are from New England on your site? Curious where? :) I'm from Maine and lived in Amesbury/Newburyport Mass for a while.. )

Here is where I am currently having a problem

**On your line 3 Open up a terminal window in the macos_burst directory.**

I can not for the life of me figure out how to do this. I started with your your instructions on how do do it myself, got homebrew installed, then MariaDB tripped me up

**Comment by beatsbears** [comment]
@ChunkyVittles if you're not very familiar with the terminal, the easiest way is probably to just find the folder right-click on the folder itself. From the menu that appears, select the bottom "Services" option. From there a new sub-menu should appear. Select "New Terminal at Folder" from that menu. See [here](https://lifehacker.com/launch-an-os-x-terminal-window-from-a-specific-folder-1466745514). 

After that a new window will open. Once it has loaded you should type the command from step 4 - `sh macos_burst_install.sh <YOUR_PASSWORD>` using a password of your choice then press ENTER. Once the script starts running just follow the instructions provided, they will likely only include hitting ENTER occasionally to continue. 

I'll try to post a video shortly, I just didn't have time in the last week. Let me know if this works.

**Comment by ChunkyVittles** [comment]
I am getting a -bash: syntax error near unexpected token 'newline' error

**Comment by ChunkyVittles** [comment]
When you wrote "...the easiest way is probably to just find the folder" - What folder are you referring to? The folder resulting from the github download?

**Comment by ChunkyVittles** [comment]
also (again sorry if this is a stupid question) - when I finally get to that terminal stage... do I include the <> symbols when entering the password? or do I just enter the password without those <>?

**Comment by beatsbears** [comment]
Is there anything else that accompanies your error?

After you download the .zip file from github and extract it (apple may do this for you), you should have a folder named macos_burst-master. That is the folder you should open a terminal for. 

Yes, you should omit the `<>`, whatever you type after the `sh macos_burst_install.sh` will be the password the wallet uses to access the database.

**Comment by ChunkyVittles** [comment]
Hi - yes - and when I rightclick on that the option "New Termianl at Folder" is not available as an option

**Comment by beatsbears** [comment]
What version of macOS are you using?

**Comment by ChunkyVittles** [comment]
10.12.6

**Comment by ChunkyVittles** [comment]
<img width="313" alt="screen shot 2018-01-16 at 6 19 44 pm" src="https://user-images.githubusercontent.com/35457225/35017242-fa4371e6-fae9-11e7-9fe9-de1667df3e3e.png">

**Comment by beatsbears** [comment]
Can you open a terminal window and type `mdfind macos_burst-master` then press ENTER. I would expect this should return something like:
```
/Users/<your name>/Downloads/macos_burst-master
/Users/<your name>/Downloads/macos_burst-master.zip
```
If the response looks like this, try typing `cd /Users/<your name>/Downloads/macos_burst-master` using your actual account name rather than `<your name>` then hit ENTER.

If that works, try typing `ls` and hit ENTER. It should return:
```
README.md		macos_burst_install.sh
```

If all of this works, you can type `sh macos_burst_install.sh <password>` to begin the installation process.

**Comment by ChunkyVittles** [comment]
yup doing it now

**Comment by ChunkyVittles** [comment]
what do you mean by "actual account name"?

**Comment by beatsbears** [comment]
In the terminal if you type `whoami` and hit enter, it will return your account name. In my case it would return `andrew` so I would type `cd /Users/andrew/Downloads/macos_burst-master`.

**Comment by ChunkyVittles** [comment]
OK just a moment

**Comment by ChunkyVittles** [comment]
This is what I'm getting "FBI-iMac:~ davidbull$ cd /Users/davidbull/Downloads/macos_burst-master
-bash: cd: /Users/davidbull/Downloads/macos_burst-master: No such file or directory
" 

Ignore the FBI thing - the name of my router is "FBI Surveillance Van #3" lol

**Comment by ChunkyVittles** [comment]
<img width="563" alt="screen shot 2018-01-16 at 6 46 16 pm" src="https://user-images.githubusercontent.com/35457225/35018001-9a12f48c-faed-11e7-9184-011d00d7d7ba.png">

**Comment by ChunkyVittles** [comment]
Theres a screen grab so you can see exactly what it is reading

**Comment by beatsbears** [comment]
What was the output of `mdfind macos_burst-master`? it sounds like maybe the .zip file wasn't extracted.

**Comment by ChunkyVittles** [comment]
moment
<img width="1154" alt="screen shot 2018-01-16 at 6 49 40 pm" src="https://user-images.githubusercontent.com/35457225/35018128-14fd74c4-faee-11e7-94e3-3b6f3482aef0.png">

**Comment by beatsbears** [comment]
ah okay, it saved to your desktop rather than downloads. The command will be `cd /Users/davidbull/Desktop/macos_burst-master`

**Comment by ChunkyVittles** [comment]
SUCCESS :)

**Comment by ChunkyVittles** [comment]
So would I now enter "sh macos_burst-install.sh PASSWORD
" while I am in that new directory?

**Comment by beatsbears** [comment]
yep!

**Comment by ChunkyVittles** [comment]
OK I just did and it reads "No such file or directory"

**Comment by ChunkyVittles** [comment]
<img width="399" alt="screen shot 2018-01-16 at 6 57 05 pm" src="https://user-images.githubusercontent.com/35457225/35018352-12783fd0-faef-11e7-8188-a87d485aadc5.png">

**Comment by beatsbears** [comment]
What is the output of `ls`?

**Comment by ChunkyVittles** [comment]
wait - when I cut and pasted your command text and just plugged it in (and changed the password of course from <PASSWORD> - it worked

**Comment by ChunkyVittles** [comment]
I dont know if I had an extra space in there or something? but now I see evertying installing - Like MariaDB....

**Comment by ChunkyVittles** [comment]
damn - no Java runtime present, requesting install. That happened after the wallet install

**Comment by ChunkyVittles** [comment]
<img width="999" alt="screen shot 2018-01-16 at 7 01 42 pm" src="https://user-images.githubusercontent.com/35457225/35018469-b7b684a2-faef-11e7-953c-805c1b1c76b8.png">

**Comment by ChunkyVittles** [comment]
theres a screenshot of where it crapped out on me -

**Comment by ChunkyVittles** [comment]
so I am downloading Java for mac OS X version 8 update 161

**Comment by ChunkyVittles** [comment]
<img width="404" alt="screen shot 2018-01-16 at 7 04 09 pm" src="https://user-images.githubusercontent.com/35457225/35018523-0d2de9e8-faf0-11e7-9a9f-5645137fdeb7.png">

**Comment by ChunkyVittles** [comment]
I cant win lol

**Comment by ChunkyVittles** [comment]
OH DUH - wait - I just re-read your instructions - I guess I am just waiting for the wallet to synchronize and open - so maybe it is working

**Comment by ChunkyVittles** [comment]
but why would it tell me "No Java runtime present, requesting install."?... Anyway - I am running out to eat - I really appreciate your help here very much and will definitely be sending you some burst!

**Comment by beatsbears** [comment]
That Java message seems suspicious. In your internet browser try going to `http://loclahost:8125/index.html` If it's actually working you should see a login page.

**Comment by ChunkyVittles** [comment]
yes I did (with Chrome)_ and there is nothing there

**Comment by ChunkyVittles** [comment]
I'm still here .. any suggestions?

**Comment by beatsbears** [comment]
Okay. So we'll need to try again. 
First you'll need to close your current terminal window and open a new one.

The follow these steps
1. `cd /Users/davidbull/Desktop/macos_burst-master`
2. `sh macos_burst_install.sh --uninstall`
3.  `brew tap caskroom/versions`
4. `brew cask search java`
5. `brew cask install java8`
6.  `sh macos_burst-install.sh PASSWORD`

This will first uninstall what was installed the first time so you have a fresh database, then try to install java8, and finally run the install script again. 

Sorry for the troubles.

**Comment by ChunkyVittles** [comment]
<img width="862" alt="screen shot 2018-01-16 at 7 16 15 pm" src="https://user-images.githubusercontent.com/35457225/35018877-bc883744-faf1-11e7-81df-81cb93861b13.png">

**Comment by ChunkyVittles** [comment]
I went to my preferences and it indicated a critical update of Java was available so I just updated

**Comment by ChunkyVittles** [comment]
weird - when I TYPE the command sh macos_burst_install.sh password - it doesnt work - when I cut and Paste it from what you wrote - it DOES work..and im typing exactly the same thing

**Comment by ChunkyVittles** [comment]
I'm getting a download Java 8 error message.. I see it when your commands are running through... is the download address correct on that?

**Comment by ChunkyVittles** [comment]
<img width="721" alt="screen shot 2018-01-16 at 7 22 27 pm" src="https://user-images.githubusercontent.com/35457225/35019037-ada65dc2-faf2-11e7-9970-bdff186235d9.png">
<img width="1106" alt="screen shot 2018-01-16 at 7 22 49 pm" src="https://user-images.githubusercontent.com/35457225/35019038-adb406ac-faf2-11e7-98d8-da809e0a6291.png">

**Comment by ChunkyVittles** [comment]
Theres a couple screenshots for you showing what is happening

**Comment by beatsbears** [comment]
Hmm, that seems to indicate that the download link for Java from the package manager is broken.. so the script isn't making any mistakes at least. 

Perhaps try running `brew update` to see if that package manager has any updated urls... I'm not sure beyond hoping that works of finding the Java8 jdk download on your own.

**Comment by ChunkyVittles** [comment]
so I need Java 8? A later version of the software wont work?

**Comment by ChunkyVittles** [comment]
Just ran brew update - and it says "Already up-to-date

**Comment by ChunkyVittles** [comment]
Any suggestion which of these Java 8's to download? :) http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html

**Comment by beatsbears** [comment]
The macOS Java SE Development Kit 8u162 one should be the one you need. But you may have problems since you already have a more Recent Java installed.

Also, make sure you run `sh macos_burst_install.sh --uninstall` between your install attempts, otherwise the database will not be set up correctly.

**Comment by ChunkyVittles** [comment]
Update - I uninstalled Java and a macos burst uninstall  - then reinstalled Java using Java 8u162. I then reinstalled macos/burst..

and everthing seems to work - until it reaches the "Initializing Burst server version 1.3.6.. I get many "could not connect... failed to initialize pool...access denied for user 'burstwallet' ..  type messages.

Also, the localhost page still fails to load. :(

**Comment by beatsbears** [comment]
That sounds like the database wasn't set up with a password correctly. 

When the `Resetting Root password for MariaDB... Press ENTER when prompted` message appears, just press ENTER, you do not need to retype your password here.

**Comment by ChunkyVittles** [comment]
Good morning

I uninstalled, then reinstalled again - and when I was presented with a MariaDB password request, I just hit ENTER...but the localhost page still will not load

However, the localhost page DOES open if I change https: to http: from the beginning of it

Also the IP address it gives me opens as well

**Comment by ChunkyVittles** [comment]
SUCCESS ! Now I want to MINE haha when are THOSE instructions coming out??

**Comment by ChunkyVittles** [comment]
So sending BURST to you will be my very first transaction - I just want to make sure I am doing it right so I am going to send you 5 to start as a test ....can you let me know when you receive them? :) then I will send you more

**Comment by beatsbears** [comment]
I hope to add scripts for plotting/plot verification/mining in the next week or so. There are many options so I'm still doing research to find the best tools and the best configurations for those tools before I publish anything. 

I appreciate the tip! I got them :)
