### ISSUE TITLE
Restarting the wallet

### ISSUE THREAD

**Issue by ChunkyVittles** [beatsbears/macos_burst#2]
Hi remember me? :)

I have another dumb question... I did get the wallet to run the last time, and it downloaded the entire blockchain etc..

But I eventually had to turn off my computer.

Now I when I turned it back on, how do I

1) restart the same wallet? Is there a terminal command to just start that same wallet? and
2) do it without downloading the entire Burst blockchain again and 
3) Isnt there an icon or something for the burst wallet to run as a stand alone application on my imac or do I have to go to the Index page each time to have it run

Thank you!

**Comment by beatsbears** [comment]
Try opening the terminal and use these commands to restart the wallet. If it hasn't been running for long it may take a few minutes to sync, but it won't need to download the whole blockchain again. I think these paths should be correct based on our last conversation.
```
cd /Users/davidbull/Desktop/macos_burst-master/burstcoin/burstcoin-1.3.6cg/
sh burst.sh
```

**Comment by ChunkyVittles** [comment]
Yup! it appears to be working thank you -
